website/auth.py
from flask import Flask,Blueprint, render_template, url_for, request, flash, redirect
from flask_login import login_user, login_required, logout_user, current_user
from .models import User
from website import db  # Importamos db desde el paquete 'website'
from werkzeug.security import generate_password_hash, check_password_hash
from wtforms import Form, StringField, PasswordField
from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp

auth = Blueprint('auth', __name__)

class SignUpForm(Form):
    first_name = StringField('Nombre', validators=[DataRequired(message='El nombre es obligatorio.'), 
                                                Length(min=3, message='El nombre debe contener mínimo 3 caracteres.'),  
                                                Regexp('^[A-Za-záéíóúÁÉÍÓÚñÑ ]+$', message='El nombre solo debe contener letras.')])
    
    last_name = StringField('Apellido', validators=[DataRequired(message='El apellido es obligatorio.'), 
                                                    Length(min=3, message='El apellido debe contener minimo 3 caracteres.'),
                                                    Regexp('^[A-Za-záéíóúÁÉÍÓÚñÑ ]+$', message='El apellido solo debe contener letras.')])
                                                    
                                                    
    email = StringField('Correo electrónico', validators=[DataRequired(message='El correo electrónico es obligatorio.'), 
                                                        Email(message='Ingrese un correo electrónico.')])
    
    
    password1 = PasswordField('Contraseña', validators=[DataRequired(message='La contraseña es obligatoria.'), 
                                                        Length(min=8, message='La contraseña debe contener mínimo 8 caracteres.'),
                                                        Regexp('^(?=.*[A-Z])(?=.*\d).{8,}$', message='La contraseña  debe contener al menos una mayúsucla y un número.')])
    
    
    password2 = PasswordField('Confirmar Contraseña', validators=[DataRequired(message='Confirme la contraseña.'), 
                                                                EqualTo('password1', message='Las contraseñas no coinciden')])


@auth.route('/iniciar_sesion', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        if not email or not password:
            flash('Por favor, complete ambos campos.', category='general_error')
            return render_template("iniciar-sesion.html")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.content'))
            else:
                flash('Contraseña incorrecta. Intente de nuevo.', category='password_error')
        else:
            flash('El email no existe.', category='email_error')
    return render_template("iniciar-sesion.html")

@auth.route('/cerrar_sesion')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/registrarse', methods=['GET', 'POST'])
def sign_up():
    form = SignUpForm(request.form)

    if request.method == 'POST' and form.validate():
        # Obtener los datos del formulario
        first_name = form.first_name.data.strip().capitalize()
        last_name = form.last_name.data.strip().capitalize()
        email = form.email.data
        password1 = form.password1.data

        # Validar si el email ya existe
        user = User.query.filter_by(email=email).first()

        if user:
            flash('El email ya existe.', category='email_error')
            return render_template('registrarse.html', form=form)
        else:
            # Crear nuevo usuario
            new_user = User(
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=generate_password_hash(password1, method='pbkdf2:sha256')
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)

            return redirect(url_for('views.home'))

    return render_template('registrarse.html', form=form) 


@auth.route('/eliminar_cuenta' , methods=['GET','POST'])
@login_required
def delete_account():
    if request.method == 'POST':
        user = current_user
        
        if user:
            db.session.delete(user)
            db.session.commit()
    
            logout_user()
    
        return redirect(url_for('auth.login'))
    return render_template('eliminar_cuenta.html')
    



from flask import render_template, request, redirect, url_for

website/templates/bienvenido.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bienvenido.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/comun.css') }}">
    <title>FlixFusion</title>
</head>
<body>
    <div class="inicio">
        <h1>Bienvenido a FlixFusion</h1>
        <a href="{{ url_for('auth.login') }}">Inicia Sesión</a>
    </div>
</body>
</html>

website/templates/contenido.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flix Fusion</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/contenido.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/comun.css') }}">

    <!-- Usamos iconos de font awesome para el nav -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>

<body>

    
    <header class="logo"></header>

    <!-- Menu de navegacion -->
    <nav id="navbar">
        <ul id="cont-nav">
            <li id="logo"><a href="{{url_for('views.content')}}"><img src="/static/img/logo-flix-fusion.png" alt=""></a>
            </li>
            <li><a href="{{url_for('views.content')}}"><i class="fas fa-home"></i></a></li>
            <li><a href="#" id="search-icon"><i class="fas fa-search search-icon"></i></a></li>
            <!--  Input cuando tocamos el icono de buscar -->
            <li id="search-container" style="display: none;">
                <div id="search-overlay" class="search-overlay">
                    <input type="text" id="search-input" placeholder="Buscar...">
                    <span class="cerrar-buscador">
                        <i class="fa-solid fa-xmark cerrar_perfil"></i>
                    </span>
                </div>
            </li>
            <!-- <li id="buy"><a href=""><i class="fa-solid fa-bag-shopping"></i></a></li> -->
            <div class="contenedor_carrito" id="contenedor_carrito">
                <li>
                    <div class="carrito-counter">0</div>
                    <img class="img-carrito"src="/static/img/carrito-de-compras.png" alt="Carrito de compras">
                </li>
            </div>
            <div class="contenedor-perfil" id="contenedor-perfil">
                <li id="perfil">
                    <a href="#">
                        <span id="mi-perfil">{{user.first_name}} {{user.last_name}}</span>
                        <!-- Mostrar la imagen de perfil -->
                        <img src="{{ url_for('static', filename='img/' + (current_user.image_file or 'spiderman.jpg')) }}"
                            alt="Imagen de perfil" width="40" height="40">
                    </a>
                </li>
            </div>
        </ul>
    </nav>

    <div id="movies-container"></div>

<!--  Menu perfil -->
    <div class="menu-perfil" id="menu-perfil">
        <div class="header-perfil">
            <h2>{{user.first_name}} {{user.last_name}}</h2>
            <img src="{{ url_for('static', filename='img/' + (current_user.image_file or 'spiderman.jpg')) }}" alt="Imagen de perfil" width="45" height="45">
            <span class="cerrar">
                <i class="fa-solid fa-xmark cerrar_perfil"></i>
            </span>
        
        </div>
        <div class="contenido-perfil">
            <ul>
                <li>Cambiar perfil</li>
                <li> <a href="{{url_for('views.account')}} ">Cuenta</a></li>
                <li>Ayuda</li>
                <li>Ajustes</li>
                <li><a href="{{url_for('auth.logout')}} ">Cerrar sesión</a></li>
            </ul>
        </div>
    </div>




    <div class="carrito" id="menu_carrito">
        <div class="header_carrito">
            <h3>Contenido del carrito</h3>
            <i class="fa-solid fa-xmark cerrar_carrito"></i>
        </div>
        <div class="carrito_items">
            </div>

            <div class="carrito_total">
                <div class="fila">
                    <strong>Tu total</strong>
                    <span class="carrito_precio_final">
                    </span>
                </div>
                <button class="btn_pagar">Pagar<i class="fa-solid fa-bag-shopping"></i></button>
                <div class="check"></div>
            </div>
        </div>
        </div>




    <!--  Contenido principal -->
    <main>
        <div class="movie-description"></div>
        <div id="moviePopup" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <div class="movie-description-content">
                    <!-- Aquí se cargará la información de la película -->
                </div>
            </div>
        </div>
        <div id="cont-slider">
            
            <div id="slider">
                <div class="sliders">
                    <img src="/static/img/fondo-1.webp" alt="El Escape">
                    <div class="text-overlay-escape">El Escape</div>
                    <div class="text-overlay-parrafo">18+  2024  -  Suspenso, Terror</div>
                </div>
                <div class="sliders">
                    <img src="/static/img/fondo-2.jpg" alt="León">
                    <div class="text-overlay-ciudad">El Peor Plan</div>
                    <div class="text-overlay-parrafo">14+  2024  -  Comedia, Accion</div>
                </div>
                <div class="sliders">
                    <img src="/static/img/fondo-3.jpg" alt="Joker">
                    <div class="text-overlay-rescatados">El Rescate</div>
                    <div class="text-overlay-parrafo">18+  2024  -  Suspenso, Accion</div>
                </div>
                <div class="sliders">
                    <img src="/static/img/fondo-4.jpg" alt="Mujer Gato">
                    <div class="text-overlay-galaxia">Galácticos</div>
                    <div class="text-overlay-parrafo">14+  2024  -  Documental</div>
                </div>
                <div class="sliders">
                    <img src="/static/img/fondo-5.jpg" alt="Un corazon">
                    <div class="text-overlay-amor">Un Corazón</div>
                    <div class="text-overlay-parrafo">16+  2024  -  Romantica</div>
                </div>
            </div>
            
        </div>

        <section id="categorias">
            <div class="container">
            </div>
        </section>


        <section class="principales">
            </section>



        <section class="proximamente">
            <h3>Proximamente...</h3>
            <div id="slider-proximamente">
                <div class="sliders-prox">
                    <img src="/static/img/proximamente-1.jpg" alt="">
                </div>
                <div class="sliders-prox">
                    <img src="/static/img/proximamente-2.jpg" alt="León">
                </div>
                <div class="sliders-prox">
                    <img src="/static/img/proximamente-3.webp" alt="Joker">
                </div>
                <div class="sliders-prox">
                    <img src="/static/img/proximamente-4.webp" alt="Mujer Gato">
                </div>
            </div>
        </section>
    </main>

    <!-- Pie de pagina -->
    <footer>
        <div class="redes">
            <h3>Nuestras redes:</h3>
        <div class="social">
            <a class="instagram"
                href="https://instagram.com"
                title="Seguinos en instagram"
                target="_blank">
            </a>
            <a class="twitter"
                href="https://twitter.com"
                title="Seguinos en twitter"
                target="_blank">
            </a>
            <a class="github"
                href="https://github.com"
                title="Seguinos en github"
                target="_blank">
            </a>
        </div>
    </div>
        <div class="container-footer">
        <div class="footer-contacto">
            <p>¿Preguntas? Llama al <a href="">0341 411 2004</a></p>
        </div>
        <div class="footer-links">
            <div class="contenido-links">
                <div id="elemento1">
                    <a href="">Preguntas Frecuentes</a>
                </div>
                <div id="elemento2">
                    <a href="">Centro de ayuda</a>
                </div>
                <div id="elemento3">
                    <a href="">Términos de uso</a>
                </div>
                <div id="elemento4">
                    <a href="">Privacidad</a>
                </div>
                <div id="elemento5">
                    <a href="">Preferencias de cookies</a>
                </div>
                <div id="elemento6">
                    <a href="">Información Corporativa</a>
                </div>
            </div>
        </div>
        <div class="footer-lenguaje">
            <select class="language-selector">
                <option value="es">Español</option>
                <option value="en">English</option>
            </select>
        </div>
    </div>
</div>

    </footer>

    <script type="module" src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>

</html>

website/templates/cuenta.html
<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/comun.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cuenta.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <title>FlixFusion</title>
</head>
<body>
    <!-- Menu de navegacion -->
    <nav id="navbar">
        <ul id="cont-nav">
            <li id="logo"><a href="{{url_for('views.content')}}"><img src="/static/img/logo-flix-fusion.png" alt=""></a></li>
            <li><a href="{{url_for('views.content')}}"><i class="fas fa-home"></i></a></li>
            <div class="contenedor-perfil" id="contenedor-perfil">
            <li id="perfil">
                <a href="#">
                    <span id="mi-perfil">{{user.first_name}} {{user.last_name}}</span>
                    <!-- Mostrar la imagen de perfil -->
                    <img src="{{ url_for('static', filename='img/' + (current_user.image_file or 'spiderman.jpg')) }}" alt="Imagen de perfil" width="40" height="40">
                </a>
            </li>
        </div>
        </ul>
    </nav>
<!--  Menu perfil -->
<div class="menu-perfil" id="menu-perfil">
    <div class="header-perfil">
        <h2>{{user.first_name}} {{user.last_name}}</h2>
        <img src="{{ url_for('static', filename='img/' + (current_user.image_file or 'spiderman.jpg')) }}" alt="Imagen de perfil" width="45" height="45">
        <span class="cerrar">
            <i class="fa-solid fa-xmark cerrar_perfil"></i>
        </span>
    
    </div>
    <div class="contenido-perfil">
        <ul>
            <li>Cambiar perfil</li>
            <li> <a href="{{url_for('views.account')}} ">Cuenta</a></li>
            <li>Ayuda</li>
            <li>Ajustes</li>
            <li><a href="{{url_for('auth.logout')}} ">Cerrar sesión</a></li>
        </ul>
    </div>
</div>
    <div class="container">
        <h1>Perfil de {{user.first_name}} {{user.last_name}}</h1>
        <p>Email: {{user.email}}</p>
        <div class="profile-section">
            <h2>Imagen actual:</h2>
            <img src="{{ url_for('static', filename='img/' + (current_user.image_file or 'spiderman.jpg')) }}" alt="Imagen de perfil" width="150">
        </div>
        <form action="{{ url_for('views.account') }}" method="POST" enctype="multipart/form-data" class="form-upload">
            <label for="imagen">Sube una nueva imagen de perfil:</label>
            <input type="file" name="imagen" id="imagen" accept="image/*">
            {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            {% if category == 'error-archivo' %}
                                <p class="text-danger">{{ message }}</p>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            <button type="submit">Actualizar Imagen</button>
        </form>
        <div id="cuenta">
            <a href="{{url_for('auth.delete_account')}}" class="logout">Eliminar cuenta</a>
            <a href="{{ url_for('auth.login') }}" class="logout">Cerrar Sesión</a>
        </div>
    </div>
   <!-- Pie de pagina -->
   <footer>
    <div class="redes">
        <h3>Nuestras redes:</h3>
    <div class="social">
        <a class="instagram"
            href="https://instagram.com"
            title="Seguinos en instagram"
            target="_blank">
        </a>
        <a class="twitter"
            href="https://twitter.com"
            title="Seguinos en twitter"
            target="_blank">
        </a>
        <a class="github"
            href="https://github.com"
            title="Seguinos en github"
            target="_blank">
        </a>
    </div>
</div>
    <div class="container-footer">
    <div class="footer-contacto">
        <p>¿Preguntas? Llama al <a href="">0341 411 2004</a></p>
    </div>
    <div class="footer-links">
        <div class="contenido-links">
            <div id="elemento1">
                <a href="">Preguntas Frecuentes</a>
            </div>
            <div id="elemento2">
                <a href="">Centro de ayuda</a>
            </div>
            <div id="elemento3">
                <a href="">Términos de uso</a>
            </div>
            <div id="elemento4">
                <a href="">Privacidad</a>
            </div>
            <div id="elemento5">
                <a href="">Preferencias de cookies</a>
            </div>
            <div id="elemento6">
                <a href="">Información Corporativa</a>
            </div>
        </div>
    </div>
    <div class="footer-lenguaje">
        <select class="language-selector">
            <option value="es">Español</option>
            <option value="en">English</option>
        </select>
    </div>
</div>
</div>

</footer>
<script src="{{ url_for('static', filename='js/perfil.js') }}"></script>
</body>
</html>

website/templates/eliminar_cuenta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/eliminar_cuenta.css') }}">
    <title>FlixFusion</title>
</head>
<body>
    <div class="container">
    <h1>FlixFusion</h1>
    <p>¿Estas seguro que deseas eliminar la cuenta?</p>
        <div id="confirmar">
            <form method="POST">
                <button type="submit" class="btn btn-danger">Sí, eliminar mi cuenta</button>
            </form>
            <button><a href="{{ url_for('views.account') }}">Cancelar</a></button>
        </div>
</div>
</body>
</html>

website/templates/iniciar-sesion.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/iniciar-sesion.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/comun.css') }}">
    <link rel="shortcut icon" href="./icono1.png" type="image/x-icon">
    <title>FlixFusion</title>
</head>
<body>
    <main>
        <!-- Titulo -->
        <header class="logo-inicio-sesion"></header>
        <!-- Login Inicio de sesion -->
        <div id="login">
            <form id="formulario" action="{{ url_for('auth.login') }}" method="post" >
                <h2>Inicia sesión</h2>
                <input class="ipt" type="email" placeholder="Ingrese el email" name="email" id="email" value ="{{ request.form.get('email', '') }}">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            {% if category == 'email_error' %}
                                <p class="text-danger">{{ message }}</p>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <input class="ipt" type="password" placeholder="Contraseña" name="password" id="password" value ="{{ request.form.get('password', '') }}">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            {% if category == 'password_error' %}
                                <p class="text-danger">{{ message }}</p>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            {% if category == 'general_error' %}
                                <p class="text-danger">{{ message }}</p>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <input id="btn" type="submit" value="Iniciar sesión">
                <a href="#" id="forget">¿Olvidaste la Contraseña?</a>
                <div id="remember">
                    <input type="checkbox">
                    <p>Recuérdame</p>
                </div>
                <p>¿Primera vez en <span>FlixFusion</span>? <a href="{{ url_for('auth.sign_up') }}">Regístrate.</a></p>
            </form>
        </div>
    </main>
    <hr id="hr">
    <!-- Pie de pagina -->
    <footer>
        <div class="redes">
            <h3>Nuestras redes:</h3>
        <div class="social">
            <a class="instagram"
                href="https://instagram.com"
                title="Seguinos en instagram"
                target="_blank">
            </a>
            <a class="twitter"
                href="https://twitter.com"
                title="Seguinos en twitter"
                target="_blank">
            </a>
            <a class="github"
                href="https://github.com"
                title="Seguinos en github"
                target="_blank">
            </a>
        </div>
    </div>
        <div class="container-footer">
        <div class="footer-contacto">
            <p>¿Preguntas? Llama al <a href="">0341 411 2004</a></p>
        </div>
        <div class="footer-links">
            <div class="contenido-links">
                <div id="elemento1">
                    <a href="">Preguntas Frecuentes</a>
                </div>
                <div id="elemento2">
                    <a href="">Centro de ayuda</a>
                </div>
                <div id="elemento3">
                    <a href="">Términos de uso</a>
                </div>
                <div id="elemento4">
                    <a href="">Privacidad</a>
                </div>
                <div id="elemento5">
                    <a href="">Preferencias de cookies</a>
                </div>
                <div id="elemento6">
                    <a href="">Información Corporativa</a>
                </div>
            </div>
        </div>
        <div class="footer-lenguaje">
            <select class="language-selector">
                <option value="es">Español</option>
                <option value="en">English</option>
            </select>
        </div>
    </div>
</div>
    </footer>
    <script src="{{ url_for('static', filename='js/error-message.js') }}"></script>
</body>
</html>

website/templates/movie_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ movie.title }}</title>
</head>
<body>
    <h1>{{ movie.title }}</h1>
    <div class="video-container">
        <iframe width="100%" height="50%" src="{{ movie.video_url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
</body>
</html>

website/templates/registrarse.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/registrarse.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/comun.css') }}">
    <title>Únete a FlixFusion!</title>
</head>
<body>
    <div class="container">
        <h1>Regístrate</h1>
        <p id="descripcion">Ingrese sus datos correspondientes.</p>
        <form id="formulario" action="{{ url_for('auth.sign_up') }}" method="post">
            <div class="form-group">
                <input type="text" placeholder="Nombre" name="first_name" id="nombre"  value ="{{ request.form.get('first_name', '') }}">
                {% if form.first_name.errors %}
                    {% for error in form.first_name.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                <input type="text" placeholder="Apellido" name="last_name" id="apellido"  value ="{{ request.form.get('last_name', '') }}">
                {% if form.last_name.errors %}
                    {% for error in form.last_name.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
            {% endif %}
            </div>
            <div class="form-group">
                <input type="email" placeholder="Email" name="email" id="email" value ="{{ request.form.get('email', '') }}">
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
            {% endif %}

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% for category, message in messages %}
                    {% if category == 'email_error' %}
                        <p class="text-danger">{{ message }}</p>
                    {% endif %}
                {% endfor %}
            {% endwith %}
            </div>
            <div class="form-group">
                <input type="password" placeholder="Contraseña" name="password1" id="contraseña"  value ="{{ request.form.get('password1', '') }}">
                {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                        <p class="text-danger">{{ error }}</p>
                {% endfor %}
            {% endif %}
            </div>
            <div class="form-group">
                <input type="password" placeholder="Repetir contraseña" name="password2" id="contraseña2" value ="{{ request.form.get('password2', '') }}">
                {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <input id="btn" type="submit" value="Registrarse">
        </form>
    </div>

    <div class="container">
        <p id="cuenta"><a href="{{ url_for('auth.login') }}">Ya tengo cuenta</a></p>
    </div>

    <hr id="hr">

    <footer>
        <div class="redes">
            <h3>Nuestras redes:</h3>
        <div class="social">
            <a class="instagram"
                href="https://instagram.com"
                title="Seguinos en instagram"
                target="_blank">
            </a>
            <a class="twitter"
                href="https://twitter.com"
                title="Seguinos en twitter"
                target="_blank">
            </a>
            <a class="github"
                href="https://github.com"
                title="Seguinos en github"
                target="_blank">
            </a>
        </div>
    </div>
        <div class="container-footer">
        <div class="footer-contacto">
            <p>¿Preguntas? Llama al <a href="">0341 411 2004</a></p>
        </div>
        <div class="footer-links">
            <div class="contenido-links">
                <div id="elemento1">
                    <a href="">Preguntas Frecuentes</a>
                </div>
                <div id="elemento2">
                    <a href="">Centro de ayuda</a>
                </div>
                <div id="elemento3">
                    <a href="">Términos de uso</a>
                </div>
                <div id="elemento4">
                    <a href="">Privacidad</a>
                </div>
                <div id="elemento5">
                    <a href="">Preferencias de cookies</a>
                </div>
                <div id="elemento6">
                    <a href="">Información Corporativa</a>
                </div>
            </div>
        </div>
        <div class="footer-lenguaje">
            <select class="language-selector">
                <option value="es">Español</option>
                <option value="en">English</option>
            </select>
        </div>
    </div>
</div>

    </footer>
    <script src="{{ url_for('static', filename='js/error-message.js') }}"></script>
</body>
</html>